<?php
$monthsfrtoen['Janvier']='January';
$monthsfrtoen['Février']='February';
$monthsfrtoen['Mars']='March';
$monthsfrtoen['Avril']='April';
$monthsfrtoen['Mai']='May';
$monthsfrtoen['Juin']='June';
$monthsfrtoen['Juillet']='July';
$monthsfrtoen['Août']='August';
$monthsfrtoen['Septembre']='September';
$monthsfrtoen['Octobre']='October';
$monthsfrtoen['Novembre']='November';
$monthsfrtoen['Décembre']='December';

$monthsfrtonb=[];
$monthsfrtonb['Janvier']=1;
$monthsfrtonb['Février']=2;
$monthsfrtonb['Mars']=3;
$monthsfrtonb['Avril']=4;
$monthsfrtonb['Mai']=5;
$monthsfrtonb['Juin']=6;
$monthsfrtonb['Juillet']=7;
$monthsfrtonb['Août']=8;
$monthsfrtonb['Septembre']=9;
$monthsfrtonb['Octobre']=10;
$monthsfrtonb['Novembre']=11;
$monthsfrtonb['Décembre']=12;